### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ColonelKai** [EuroCraftDevelopment/EuroStates#6]
# Systems

## Battle
Zone of the town is just a radius, calculate by distance.
- [x] Starting of a battle (must be in the zone of the town)
- [x] Kill adding 50 points.
- [x] Every 10 minutes, it adding 10 points per person in the battle zone.
- [x] End the battle after 6 hours.

## Chat

- [ ] Global Chat
- [ ] Local Chat
- [ ] National Change
- [ ] Alliance Change

# Commands
### State Admin Commands

- [x] /state create [statename] [stateleader] [StateCapitalTownTag/Name]
- [x] /state delete [statename/tag]
- [x] /state forceedit name [statename/tag] [newname]
- [x] /state forceedit tag [statename/tag] [newtag]
- [x] /state forceedit color [statename/tag] [newcolor]
- [x] /state forceedit userprefix [statename/tag] [member] [prefix]
- [x] /state forceedit regradius [statename/tag] [int radius]
- [x] /state forcehandover [statename/tag] [newleader]

### State Leader Commands

- [x] /state edit name [newname]
- [x] /state edit tag [newtag]
- [x] /state edit color [newcolor]
- [x] /state edit userprefix [member] [prefix]
- [x] /state edit currency [currencyname]
- [x] /state invite [player]
- [ ] /state handover [player] [confirm]
- [ ] /state sharetech [statetag/statename]
- [ ]  /state relations [statetag/statename] [war/ally/neutral]
- [ ] /state print [amount]

### State Member Commands

- [x] /state leave

### State Global Commands

- [x] /state [statetag/statename]
- [x] /state seetech [statetag/name] (if we want to do pages [page] too)
- [x] /state join [statetag/statename]

### Town Admin Commands
- [x] /town create [townname] [townleader]
- [x] /town delete [townname/tag]
- [ ] /town forceedit name [townname/tag] [newname]
- [ ] /town forceedit tag [townname/tag] [newtag]

### Town Mayor Commands

- [ ] /town edit name [newname]
- [ ] /town edit tag [newtag]
- [ ] /town edit center

### Town Global Commands

- [x] /town [towntag/name]
- [x] /town getlocation [towntag/name]

### Technology Admin Commands
- [x] /tech create [techid] (Could we make a sequence???)
- [x] /tech assign [statetag/name] [techid]
- [ ] /tech unassign [statetag/name] [techid]

### Chat Commands
- [ ] /chat [n/nation]
- [ ] /chat [g/global]
- [ ] /chat [a/ally]
- [ ] /chat [l/local]

### State Leader Battle Commands
- [ ] /battle begin [towntag/name]
- [ ] /battle surrender [towntag/name] 

### Global Battle Commands
- [ ] /battle viewinfo [towntag/name]
- [ ] /battle join [battleid] [side]
